version: '3.7'
services:
  database:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysqlVol:/var/lib/mysql
    networks:
      - netwrk
    environment:
      MYSQL_ROOT_PASSWORD: mysqltooR

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - database
    networks:
      - netwrk
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: mysecret123
        databases:
          default:
            connector: mysql
            host: database
            user: root
            password: mysqltooR
            rawAccess: true
            port: 3306
            migrations: true

  server:
    build: ./server
    ports:
      - '4000:4000'
    depends_on:
      - database
    networks:
      - netwrk
    environment:
      PRISMA_URL: prisma

  # frontend:
  #   build: ./
  #   ports:
  #     - '3000:80'
  #   depends_on:
  #     - server
  #   networks:
  #     - netwrk
  #   # env_file:
  #   #   - ./.env
  #   environment:
  #     PORT: 80
  #     SERVER_URL: server

volumes:
  mysqlVol:

networks:
  netwrk:
